"""initial_schema

Revision ID: dae1c633f2ac
Revises: 
Create Date: 2026-03-28 07:53:06.898737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae1c633f2ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'trader', name='userrole'), nullable=False),
    sa.Column('paper', sa.Boolean(), nullable=False),
    sa.Column('alpaca_key_env', sa.String(length=128), nullable=True),
    sa.Column('alpaca_secret_env', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gate_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('gate', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gate_log', schema=None) as batch_op:
        batch_op.create_index('idx_gate_user_gate', ['user_id', 'gate'], unique=False)
        batch_op.create_index('idx_gate_user_time', ['user_id', 'logged_at'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('buying_power', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_user_time', ['user_id', 'captured_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='tradeside'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('partial_taken', sa.Boolean(), nullable=False),
    sa.Column('trail_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('idx_position_user', ['user_id'], unique=False)

    op.create_table('regime_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Enum('bullish', 'neutral', 'bearish', name='regimelabel'), nullable=False),
    sa.Column('spy_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('qqq_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('vix', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_vector', src.db.vector_type.TiDBVector(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regime_log', schema=None) as batch_op:
        batch_op.create_index('idx_regime_user_time', ['user_id', 'logged_at'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='tradeside'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_vector', src.db.vector_type.TiDBVector(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('idx_trade_user', ['user_id'], unique=False)
        batch_op.create_index('idx_trade_user_time', ['user_id', 'exited_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('idx_trade_user_time')
        batch_op.drop_index('idx_trade_user')

    op.drop_table('trades')
    with op.batch_alter_table('regime_log', schema=None) as batch_op:
        batch_op.drop_index('idx_regime_user_time')

    op.drop_table('regime_log')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('idx_position_user')

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshot_user_time')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('gate_log', schema=None) as batch_op:
        batch_op.drop_index('idx_gate_user_time')
        batch_op.drop_index('idx_gate_user_gate')

    op.drop_table('gate_log')
    op.drop_table('users')
    # ### end Alembic commands ###
